site_name: Python-tutoring

theme:
  name: material
  features:
    - content.code.copy

nav:
  # - "Занятие 1. Что такое программирование?":
  #   - lesson1/main.md
  - lesson1/main.md
  - lesson2/main.md
  - lesson3/lesson3.md
  - lesson4/lesson4.md
  - lesson5/lesson5.md
  - lesson6/lesson6.md
  - lesson7/lesson7.md
  - lesson8/lesson8.md
  - lesson9/lesson9.md
  - lesson10/lesson10.md
  - lesson11/lesson11.md
  - lesson12/lesson12.md
  - lesson12_modules/lesson12_modules.md
  - lesson14/lesson14.md
  - lesson15_read_files/lesson15_read_files.md
  - lesson16_modules_minecraft/lesson16.md
  - lesson17/lesson17.md
  - lesson18/lesson18.md
  - lesson19/lesson19.md
  - lesson20/lesson20.md
  - lesson21/lesson21.md
  - lesson22/lesson22.md
  - lesson23/lesson23.md
  - lesson24/lesson24.md
  - lesson25/lesson25.md
  - lesson26/lesson26.md
  - lesson27/lesson27.md
  - lesson28/lesson28.md
  - lesson29/lesson29.md
  - lesson30/lesson30.md
  - lesson31/lesson31.md
  - lesson32/lesson32.md
  - lesson33/lesson33.md
  - lesson34/lesson34.md
  - lesson35/lesson35.md
  - lesson36/lesson36.md
  - lesson37_htmlcss_project/lesson37.md
  - lesson38/lesson38.md
  - lesson39/lesson39.md
  - lesson40/lesson40.md
  - lesson41/lesson41.md
  - lesson42/lesson42.md
  - lesson43/lesson43.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search
  - autolinks

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css