site_name: Python-tutoring

theme:
  name: material
  features:
    - content.code.copy

nav:
  # - "Занятие 1. Что такое программирование?":
  #   - lesson1/main.md
  - lesson1/main.md
  - lesson2/main.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - autolinks 