site_name: Python-tutoring

theme:
  name: material
  features:
    - content.code.copy

nav:
  - "Занятие 1. Что такое программирование?":
    - lesson1/main.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences